/**
 * P0-1 seed-fidelity harness. Loads the daemon-equivalent seeds (seeds.json,
 * generated by the real serializeXtermViewport logic) and replays each into BOTH
 * the wterm-ghostty and xterm backends via the production seed path:
 *   reset()  → write(seedAnsi)  → [optional] write(liveAnsi)
 * exactly mirroring CliTerminalPane.tsx seedTerminal (reset then write) +
 * live-incremental continuation.
 *
 * Query params:
 *   ?case=<name>&backend=<wterm|xterm>
 * Renders a single terminal so headless Chrome can screenshot each combo cleanly.
 */
import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
// Load wterm structural CSS (the PoC renderer omits it; P0-2 will wire it
// properly). Needed here so the alt-screen box layout/scroll renders as intended
// for a fair fidelity comparison.
import '@wterm/dom/css';
import { TerminalView } from '../src/index';
import type { TerminalRendererHandle, TerminalRendererBackend } from '../src/index';
import seeds from './seeds.json';

type SeedCase = { cols: number; rows: number; seed: string; cursor: { row: number; col: number }; live: string | null };
const SEEDS = seeds as Record<string, SeedCase>;

function App() {
  const params = new URLSearchParams(location.search);
  const caseName = params.get('case') || Object.keys(SEEDS)[0];
  const backend = (params.get('backend') === 'xterm' ? 'xterm' : 'wterm') as TerminalRendererBackend;
  const sc = SEEDS[caseName];

  const handleRef = useRef<TerminalRendererHandle | null>(null);
  const [phase, setPhase] = useState<'idle' | 'seeded' | 'live'>('idle');

  useEffect(() => {
    if (!sc) return;
    let t2: any;
    // Production seed path: resize → reset → write(seed). (CliTerminalPane:254,257,258)
    const t1 = setTimeout(() => {
      const h = handleRef.current;
      if (!h) return;
      h.resize(sc.cols, sc.rows);
      h.reset();
      h.write(sc.seed);
      setPhase('seeded');
      // Mark seeded for screenshot; then live-incremental continuation.
      if (sc.live) {
        t2 = setTimeout(() => {
          handleRef.current?.write(sc.live as string);
          setPhase('live');
        }, 1200);
      }
    }, 800);
    return () => { clearTimeout(t1); clearTimeout(t2); };
  }, [caseName, backend]);

  if (!sc) return <div style={{ color: '#fff', padding: 16 }}>unknown case: {caseName}</div>;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <div data-testid="meta" style={{ color: '#cdd6f4', fontSize: 12, padding: '4px 8px', fontFamily: 'monospace' }}>
        case=<b data-testid="case">{caseName}</b> backend=<b data-testid="backend">{backend}</b> phase=<b data-testid="phase">{phase}</b> ({sc.cols}×{sc.rows})
      </div>
      <div style={{ flex: 1, minHeight: 0 }}>
        <TerminalView
          key={`${caseName}:${backend}`}
          ref={handleRef}
          backend={backend}
          onInput={() => {}}
          fontSize={14}
          sizingMode="measured"
        />
      </div>
    </div>
  );
}

createRoot(document.getElementById('root')!).render(<App />);
