export const DEFAULT_CDP_SCAN_INTERVAL_MS = 30_000;
export const DEFAULT_CDP_DISCOVERY_INTERVAL_MS = 30_000;

export const DEFAULT_STATUS_INITIAL_REPORT_DELAY_MS = 2_000;
export const DEFAULT_STATUS_SERVER_REPORT_INTERVAL_MS = 30_000;
export const DEFAULT_STATUS_P2P_REPORT_INTERVAL_MS = 5_000;

export const MIN_MACHINE_RUNTIME_SUBSCRIPTION_INTERVAL_MS = 5_000;
export const DEFAULT_MACHINE_RUNTIME_SUBSCRIPTION_INTERVAL_MS = 15_000;

export const MIN_SESSION_HOST_DIAGNOSTICS_SUBSCRIPTION_INTERVAL_MS = 5_000;
export const DEFAULT_SESSION_HOST_DIAGNOSTICS_SUBSCRIPTION_INTERVAL_MS = 10_000;

export const DEFAULT_SESSION_HOST_READY_TIMEOUT_MS = 15_000;

export const STANDALONE_CDP_SCAN_INTERVAL_MS = 15_000;
