export const DEFAULT_MACHINE_RUNTIME_REFRESH_MS = 15_000
export const DEFAULT_MACHINE_RUNTIME_FRESH_MS = 15_000

export const DEFAULT_SESSION_HOST_DIAGNOSTICS_LIMIT = 12
export const DEFAULT_SESSION_HOST_DIAGNOSTICS_INTERVAL_MS = 8_000
export const SESSION_HOST_DIAGNOSTICS_INITIAL_TIMEOUT_MS = 4_000
