import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

describe('CLI terminal measured layout plumbing', () => {
  it('passes sizingMode through the lazy CliTerminal wrapper and flushes pending terminal work without relying on the opener window rAF', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/CliTerminal.tsx'), 'utf8')
    expect(source.includes("sizingMode = 'measured'") || source.includes("sizingMode='measured'")).toBe(true)
    expect(source.includes('sizingMode={sizingMode}')).toBe(true)
    expect(source.includes('const frame = requestAnimationFrame(() =>')).toBe(false)
    expect(source.includes('flushPending();')).toBe(true)
  })

  it('reuses the shared ChatInputBar in CliTerminalPane so terminal/chat input height stays aligned', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/CliTerminalPane.tsx'), 'utf8')
    expect(source.includes("import ChatInputBar from './ChatInputBar'") || source.includes("import ChatInputBar from \"./ChatInputBar\"")).toBe(true)
    expect(source.includes('<ChatInputBar')).toBe(true)
    expect(source.includes('isActive={isInputActive && isVisible}')).toBe(true)
    expect(source.includes('animateVisibility={false}')).toBe(true)
  })

  it('keeps CLI chat and terminal panes mounted in the same measured slot instead of display-none toggling the terminal', () => {
    const paneGroupSource = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/PaneGroupContent.tsx'), 'utf8')
    const chatPaneSource = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/ChatPane.tsx'), 'utf8')

    expect(paneGroupSource.includes("display: isCliTerminal ? 'flex' : 'none'")).toBe(false)
    expect(paneGroupSource.includes('{!isCliTerminal && (')).toBe(false)
    expect(paneGroupSource.includes("visibility: showTerminalPane ? 'visible' : 'hidden'")).toBe(true)
    expect(paneGroupSource.includes("visibility: showChatPane ? 'visible' : 'hidden'")).toBe(true)
    expect(paneGroupSource.includes('const terminalPaneVisible = getPaneGroupContentChildVisibility(isVisible, isCliTerminal)')).toBe(true)
    expect(paneGroupSource.includes('const chatPaneVisible = getPaneGroupContentChildVisibility(isVisible, showChatPane)')).toBe(true)
    expect(paneGroupSource.includes('isVisible={terminalPaneVisible}')).toBe(true)
    expect(paneGroupSource.includes('isVisible={chatPaneVisible}')).toBe(true)
    expect(paneGroupSource.includes('isInputActive={isInputActive && terminalPaneVisible}')).toBe(true)
    expect(paneGroupSource.includes('isInputActive={isInputActive && chatPaneVisible}')).toBe(true)
    expect(chatPaneSource.includes('isVisible?: boolean')).toBe(true)
    expect(chatPaneSource.includes('enabled: isVisible && !!activeConv.sessionId')).toBe(true)
  })

  it('keeps dashboard terminal panes in measured sizing without fit fallbacks and keeps zoom in the pane wrapper instead of xterm font-size feedback', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/CliTerminalPane.tsx'), 'utf8')
    expect(source.includes('shouldPreferFitCliTerminal')).toBe(false)
    expect(source.includes("effectiveTerminalSizingMode === 'fit'")).toBe(false)
    expect(source.includes('zoom: terminalScale')).toBe(true)
    expect(source.includes('transform: `scale(${terminalScale})`')).toBe(false)
    expect(source.includes('fontSize={terminalFontSize}')).toBe(false)
    expect(source.includes('const terminalFontSize = Number((13 * terminalScale).toFixed(2));')).toBe(false)
  })

  it('always requests a fresh runtime snapshot after replaying a hidden buffered snapshot on visibility restore, and replays large terminal buffers in frame-sized chunks instead of one giant write', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/CliTerminalPane.tsx'), 'utf8')
    expect(source.includes('const pendingSnapshot = pendingHiddenSnapshotRef.current;')).toBe(true)
    expect(source.includes('seedTerminal(pendingSnapshot.text, pendingSnapshot.seq, pendingSnapshot.cols, pendingSnapshot.rows);')).toBe(true)
    expect(source.includes('void requestRuntimeSnapshot();')).toBe(true)
    expect(source.includes('} else if (daemonRouteId && connectionManager.getState?.(daemonRouteId) === \'connected\') {')).toBe(false)
    expect(source.includes('const MAX_TERMINAL_WRITE_CHARS_PER_FRAME = 32 * 1024;')).toBe(true)
    expect(source.includes('const nextChunk = queuedOutput.slice(0, MAX_TERMINAL_WRITE_CHARS_PER_FRAME);')).toBe(true)
    expect(source.includes('pendingLiveOutputRef.current = queuedOutput.slice(nextChunk.length);')).toBe(true)
    expect(source.includes('if (pendingLiveOutputRef.current.length > 0) {')).toBe(true)
    expect(source.includes('scheduleFlushPendingLiveOutput();')).toBe(true)
  })

  it('routes terminal-mode sends through the same handleSendChat path as chat mode', () => {
    const terminalSource = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/CliTerminalPane.tsx'), 'utf8')
    const chatSource = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/ChatPane.tsx'), 'utf8')
    expect(chatSource.includes('onSend={handleSendChat}')).toBe(true)
    expect(terminalSource.includes('return handleSendChat(message);')).toBe(true)
    expect(terminalSource.includes('if (sendBlockMessage) return false;')).toBe(true)
  })

  it('does not mark the terminal runtime ready just because P2P connected; readiness comes from snapshot or live output', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/CliTerminalPane.tsx'), 'utf8')
    expect(source.includes("setRuntimeReady(true);\n            connectionManager.requestRuntimeSnapshot?.(daemonRouteId, sessionId).catch(() => {});")).toBe(false)
    expect(source.includes('const requestRuntimeSnapshot = async () => {')).toBe(true)
    expect(source.includes('const snapshotResult = await connectionManager.requestRuntimeSnapshot?.(daemonRouteId, sessionId);')).toBe(true)
    expect(source.includes('setRuntimeStatusMessage(`Runtime terminal unavailable: ${snapshotResult.error}`);')).toBe(true)
  })

  it('uses an outer pan surface only when manual zoom grows beyond the fitted terminal scale, sizes that pan surface from scaled intrinsic dimensions, and avoids eager auto-grow after the first fit', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/CliTerminalPane.tsx'), 'utf8')
    expect(source.includes('const fittedTerminalScale = getAutoTerminalScale();')).toBe(true)
    expect(source.includes('const safeTerminalScale = Number.isFinite(terminalScale) && terminalScale > 0 ? terminalScale : 1;')).toBe(false)
    expect(source.includes('const isManualZoomedIn = terminalScaleTouchedRef.current && terminalScale > fittedTerminalScale;')).toBe(true)
    expect(source.includes('const hasOverflowedTerminalSurface = terminalIntrinsicViewport.width > terminalViewport.width + 1')).toBe(false)
    expect(source.includes('const shouldCenterTerminalSurface')).toBe(false)
    expect(source.includes("isManualZoomedIn ? 'w-full h-full overflow-auto rounded-lg overscroll-contain' : 'w-full h-full overflow-hidden rounded-lg overscroll-contain'")).toBe(true)
    expect(source.includes("hasOverflowedTerminalSurface ? 'w-full h-full overflow-x-auto overflow-y-hidden rounded-lg overscroll-contain' : 'w-full h-full overflow-hidden rounded-lg overscroll-contain'")).toBe(false)
    expect(source.includes("display: 'flex'")).toBe(false)
    expect(source.includes("alignItems: 'flex-end'")).toBe(false)
    expect(source.includes('const scaledTerminalWidth = Number.isFinite(terminalIntrinsicViewport.width) && terminalIntrinsicViewport.width > 0')).toBe(true)
    expect(source.includes('const scaledTerminalHeight = Number.isFinite(terminalIntrinsicViewport.height) && terminalIntrinsicViewport.height > 0')).toBe(true)
    expect(source.includes("width: scaledTerminalWidth > 0 ? `${scaledTerminalWidth}px` : '100%'" )).toBe(true)
    expect(source.includes("height: scaledTerminalHeight > 0 ? `${scaledTerminalHeight}px` : '100%'" )).toBe(true)
    expect(source.includes("minWidth: '100%'" )).toBe(true)
    expect(source.includes("minHeight: '100%'" )).toBe(true)
    expect(source.includes('scrollTop = scroller.scrollHeight - scroller.clientHeight')).toBe(true)
    expect(source.includes('if (!isManualZoomedIn) return;')).toBe(true)
    expect(source.includes('const nextScale = Math.max(fittedTerminalScale, Number((scale - 0.1).toFixed(2)));')).toBe(true)
    expect(source.includes('const nextScale = Math.max(MIN_TERMINAL_SCALE, Number((scale - 0.1).toFixed(2)));')).toBe(false)
    expect(source.includes('const TERMINAL_AUTO_SCALE_CHANGE_THRESHOLD = 0.05;')).toBe(true)
    expect(source.includes('const terminalAutoScaleInitializedRef = useRef(false);')).toBe(true)
    expect(source.includes('setTerminalScale(getAutoTerminalScale());')).toBe(false)
    expect(source.includes('if (!terminalAutoScaleInitializedRef.current) {')).toBe(true)
    expect(source.includes('const shouldAutoShrink = nextScale < currentScale - TERMINAL_AUTO_SCALE_CHANGE_THRESHOLD;')).toBe(true)
    expect(source.includes('return shouldAutoShrink ? nextScale : currentScale;')).toBe(true)
  })

  it('updates xterm font size in place, keeps detached popouts off WebGL, and drives repaint scheduling through the popout owner window', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../../terminal-render-web/src/index.tsx'), 'utf8')
    expect(source.includes('term.options.fontSize = fontSize')).toBe(true)
    expect(source.includes('term.refresh(0, Math.max(0, term.rows - 1));')).toBe(true)
    expect(source.includes('}, [fontSize, sizingMode]);')).toBe(false)
    expect(source.includes('}, [sizingMode]);')).toBe(true)
    expect(source.includes('const ownerWindow = containerRef.current?.ownerDocument?.defaultView')).toBe(true)
    expect(source.includes("const isDetachedPopoutWindow = ownerWindow?.location?.pathname === '/popout.html'")).toBe(true)
    expect(source.includes("|| ownerWindow?.location?.pathname?.endsWith('/popout.html')")).toBe(true)
    expect(source.includes('|| !!ownerWindow?.opener;')).toBe(true)
    expect(source.includes('if (!isDetachedPopoutWindow) {')).toBe(true)
    expect(source.includes('const webglAddon = new WebglAddon();')).toBe(true)
    expect(source.includes('const getOwnerWindow = () => containerRef.current?.ownerDocument?.defaultView || window;')).toBe(true)
    expect(source.includes('return ownerWindow.requestAnimationFrame(callback);')).toBe(true)
    expect(source.includes('const activeElement = containerRef.current?.ownerDocument?.activeElement;')).toBe(true)
    expect(source.includes('const ResizeObserverCtor = container?.ownerDocument?.defaultView?.ResizeObserver;')).toBe(true)
    expect(source.includes("ownerWindow.addEventListener('pageshow', repaint);")).toBe(true)
    expect(source.includes("ownerDoc.addEventListener('visibilitychange', repaint);")).toBe(true)
    expect(source.includes("if (sizingMode === 'fit') applyFitIfEnabled(false);")).toBe(true)
    expect(source.includes('refreshTerminalSurface();')).toBe(true)
  })

  it('tunes xterm scrolling instead of relying on outer container scrolling', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../../terminal-render-web/src/index.tsx'), 'utf8')
    expect(source.includes('scrollSensitivity:')).toBe(true)
    expect(source.includes('fastScrollSensitivity:')).toBe(true)
    expect(source.includes('smoothScrollDuration:')).toBe(true)
    expect(source.includes('scrollOnUserInput:')).toBe(true)
  })

  it('adds terminal chrome polish for cursor, wrapper padding, and scrollbar styling without making xterm measure against the padded box', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../../terminal-render-web/src/index.tsx'), 'utf8')
    expect(source.includes('cursorWidth:')).toBe(true)
    expect(source.includes("className=\"adhdev-terminal-renderer-mount h-full w-full\"")).toBe(true)
    expect(source.includes('padding:')).toBe(true)
    expect(source.includes('ref={containerRef}')).toBe(true)
    expect(source.includes('scrollbar-width: thin')).toBe(true)
    expect(source.includes('::-webkit-scrollbar-thumb')).toBe(true)
  })

  it('marks the xterm viewport as touch-scrollable on mobile instead of requiring scrollbar dragging', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../../terminal-render-web/src/index.tsx'), 'utf8')
    expect(source.includes('-webkit-overflow-scrolling: touch')).toBe(true)
    expect(source.includes('touch-action: pan-y')).toBe(true)
  })

  it('uses shared terminal size constants and boots the browser terminal at 80x32', () => {
    const source = fs.readFileSync(path.join(import.meta.dirname, '../../../terminal-render-web/src/index.tsx'), 'utf8')
    expect(source.includes("DEFAULT_SESSION_HOST_COLS")).toBe(true)
    expect(source.includes("DEFAULT_SESSION_HOST_ROWS")).toBe(true)
    expect(source.includes("const DEFAULT_TERMINAL_ROWS = 24;")).toBe(false)
    expect(source.includes("const DEFAULT_TERMINAL_COLS = 80;")).toBe(false)
    expect(source.includes('rows: DEFAULT_SESSION_HOST_ROWS')).toBe(true)
    expect(source.includes('cols: DEFAULT_SESSION_HOST_COLS')).toBe(true)
  })

  it('reports measured xterm viewport dimensions back to the dashboard so autoscale can fit the real terminal surface without feeding back through already-scaled dimensions, and keeps detached popout scheduling/observers on the owner window', () => {
    const terminalSource = fs.readFileSync(path.join(import.meta.dirname, '../../../terminal-render-web/src/index.tsx'), 'utf8')
    const paneSource = fs.readFileSync(path.join(import.meta.dirname, '../../src/components/dashboard/CliTerminalPane.tsx'), 'utf8')

    expect(terminalSource.includes('onViewportMetrics?: (metrics: { width: number; height: number }) => void')).toBe(true)
    expect(terminalSource.includes("containerRef.current?.querySelector('.xterm-screen')")).toBe(true)
    expect(terminalSource.includes("containerRef.current?.querySelector('.xterm-viewport')")).toBe(true)
    expect(terminalSource.includes('TERMINAL_CHROME_PADDING_X')).toBe(true)
    expect(terminalSource.includes('TERMINAL_CHROME_PADDING_Y')).toBe(true)
    expect(terminalSource.includes('let width = Math.max(target.clientWidth || 0, target.scrollWidth || 0)')).toBe(true)
    expect(terminalSource.includes('let height = Math.max(target.clientHeight || 0, target.scrollHeight || 0)')).toBe(true)
    expect(terminalSource.includes('width += TERMINAL_CHROME_PADDING_X * 2')).toBe(true)
    expect(terminalSource.includes('height += TERMINAL_CHROME_PADDING_Y * 2')).toBe(true)
    expect(terminalSource.includes('onViewportMetricsRef.current?.({ width, height })')).toBe(true)
    expect(terminalSource.includes('const getOwnerWindow = () => containerRef.current?.ownerDocument?.defaultView || window;')).toBe(true)
    expect(terminalSource.includes('return ownerWindow.requestAnimationFrame(callback);')).toBe(true)
    expect(terminalSource.includes('const activeElement = containerRef.current?.ownerDocument?.activeElement;')).toBe(true)
    expect(terminalSource.includes('const ResizeObserverCtor = container?.ownerDocument?.defaultView?.ResizeObserver;')).toBe(true)

    expect(paneSource.includes('const [terminalIntrinsicViewport, setTerminalIntrinsicViewport]')).toBe(true)
    expect(paneSource.includes('const intrinsicWidth = terminalIntrinsicViewport.width')).toBe(true)
    expect(paneSource.includes('const intrinsicHeight = terminalIntrinsicViewport.height')).toBe(true)
    expect(paneSource.includes('const widthRatio = terminalViewport.width / intrinsicWidth')).toBe(true)
    expect(paneSource.includes('const heightRatio = terminalViewport.height / intrinsicHeight')).toBe(true)
    expect(paneSource.includes('const unscaledWidth = renderedWidth / safeTerminalScale')).toBe(false)
    expect(paneSource.includes('const unscaledHeight = renderedHeight / safeTerminalScale')).toBe(false)
    expect(paneSource.includes('onViewportMetrics={setTerminalIntrinsicViewport}')).toBe(true)
    expect(paneSource.includes('const getOwnerWindow = () => terminalViewportRef.current?.ownerDocument?.defaultView')).toBe(true)
    expect(paneSource.includes('frameId: ownerWindow.requestAnimationFrame(callback),')).toBe(true)
    expect(paneSource.includes('const ResizeObserverCtor = container?.ownerDocument?.defaultView?.ResizeObserver;')).toBe(true)
  })
})
