import { describe, expect, it } from 'vitest'
import {
  DEFAULT_CDP_SCAN_INTERVAL_MS,
  DEFAULT_CDP_DISCOVERY_INTERVAL_MS,
  DEFAULT_STATUS_INITIAL_REPORT_DELAY_MS,
  DEFAULT_STATUS_SERVER_REPORT_INTERVAL_MS,
  DEFAULT_STATUS_P2P_REPORT_INTERVAL_MS,
  DEFAULT_MACHINE_RUNTIME_SUBSCRIPTION_INTERVAL_MS,
  MIN_MACHINE_RUNTIME_SUBSCRIPTION_INTERVAL_MS,
  DEFAULT_SESSION_HOST_DIAGNOSTICS_SUBSCRIPTION_INTERVAL_MS,
  MIN_SESSION_HOST_DIAGNOSTICS_SUBSCRIPTION_INTERVAL_MS,
  DEFAULT_SESSION_HOST_READY_TIMEOUT_MS,
  DEV_SERVER_PORT,
  DEFAULT_DAEMON_PORT,
} from '../src/index.js'

describe('runtime defaults', () => {
  it('exports shared runtime defaults for ports and timing policy', () => {
    expect(DEFAULT_DAEMON_PORT).toBe(19_222)
    expect(DEV_SERVER_PORT).toBe(19_280)
    expect(DEFAULT_CDP_SCAN_INTERVAL_MS).toBe(30_000)
    expect(DEFAULT_CDP_DISCOVERY_INTERVAL_MS).toBe(30_000)
    expect(DEFAULT_STATUS_INITIAL_REPORT_DELAY_MS).toBe(2_000)
    expect(DEFAULT_STATUS_SERVER_REPORT_INTERVAL_MS).toBe(30_000)
    expect(DEFAULT_STATUS_P2P_REPORT_INTERVAL_MS).toBe(5_000)
    expect(MIN_MACHINE_RUNTIME_SUBSCRIPTION_INTERVAL_MS).toBe(5_000)
    expect(DEFAULT_MACHINE_RUNTIME_SUBSCRIPTION_INTERVAL_MS).toBe(15_000)
    expect(MIN_SESSION_HOST_DIAGNOSTICS_SUBSCRIPTION_INTERVAL_MS).toBe(5_000)
    expect(DEFAULT_SESSION_HOST_DIAGNOSTICS_SUBSCRIPTION_INTERVAL_MS).toBe(10_000)
    expect(DEFAULT_SESSION_HOST_READY_TIMEOUT_MS).toBe(15_000)
  })
})
