/**
 * Source of the statusline wrapper script, emitted to disk by `install`.
 *
 * This is shipped as a string rather than a checked-in `.mjs` file because it
 * must survive bundling: daemon-cloud bundles daemon-core inline, so a sibling
 * script file would not exist next to the built output. A string constant is
 * carried into the bundle verbatim and written out at install time.
 *
 * ── Why this script is written defensively ──
 * Claude Code renders the *stdout* of this process as the user's status line,
 * and a non-zero exit or empty output blanks that line entirely. The wrapper
 * therefore has one hard obligation that outranks collecting quota: reproduce
 * the original command's stdout and exit 0. Every quota operation is wrapped so
 * that a failure in it can never reach the exit code or the output stream.
 *
 * Specifics that are load-bearing:
 *  - stdin is read *once* into memory, then re-fed to the child. The original
 *    command usually consumes stdin itself (`input=$(cat)`), so a pipe that has
 *    already been drained by us would hand it nothing.
 *  - the child runs through a shell, because Claude Code's own `command` is a
 *    shell string that may contain pipes, quotes and `$(...)`.
 *  - our stdout is byte-for-byte the child's stdout. No trailing newline is
 *    added: statuslines commonly end with a reset escape and no newline.
 *  - the child's stderr is forwarded to our stderr, which Claude Code only
 *    surfaces under `--debug`, so behaviour under diagnosis is unchanged.
 *  - the child's exit code is deliberately NOT propagated. If the user's own
 *    statusline command fails we still exit 0 with whatever it printed; that
 *    matches what the user would have seen anyway and keeps our wrapper from
 *    turning a partial output into a blank line.
 */
'use strict';

/**
 * The wrapper script.
 *
 * `__ADHDEV_SNAPSHOT_PATH__`, `__ADHDEV_EXTRA_SNAPSHOT_PATHS__` and
 * `__ADHDEV_ORIGINAL_COMMAND__` are substituted at install time by
 * `renderWrapperScript`.
 */
const WRAPPER_TEMPLATE = String.raw`#!/usr/bin/env node
// Generated by ADHDev — do not edit.
//
// Wraps the user's Claude Code statusline command: passes the statusline JSON
// through untouched and reproduces the original output, while recording the
// rate_limits block for adhdev to report as provider quota.
//
// Remove with: adhdev quota claude:uninstall

import { spawn } from 'node:child_process';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const SNAPSHOT_PATH = __ADHDEV_SNAPSHOT_PATH__;
const EXTRA_SNAPSHOT_PATHS = __ADHDEV_EXTRA_SNAPSHOT_PATHS__;
const ORIGINAL_COMMAND = __ADHDEV_ORIGINAL_COMMAND__;
const SNAPSHOT_VERSION = __ADHDEV_SNAPSHOT_VERSION__;
const MIN_WRITE_INTERVAL_MS = __ADHDEV_MIN_WRITE_INTERVAL_MS__;
const MAX_WRITE_INTERVAL_MS = __ADHDEV_MAX_WRITE_INTERVAL_MS__;

function readStdin() {
    return new Promise((resolve) => {
        const chunks = [];
        process.stdin.on('data', (chunk) => chunks.push(chunk));
        process.stdin.on('end', () => resolve(Buffer.concat(chunks)));
        // A statusline invocation with no stdin must not hang the prompt.
        process.stdin.on('error', () => resolve(Buffer.concat(chunks)));
    });
}

function toFiniteNumber(value) {
    if (typeof value === 'number') return Number.isFinite(value) ? value : null;
    if (typeof value === 'string' && value.trim() !== '') {
        const parsed = Number(value);
        return Number.isFinite(parsed) ? parsed : null;
    }
    return null;
}

function toResetMs(value) {
    const seconds = toFiniteNumber(value);
    if (seconds === null || seconds <= 0) return null;
    return seconds > 1e11 ? seconds : Math.round(seconds * 1000);
}

function parseWindow(raw) {
    if (typeof raw !== 'object' || raw === null) return null;
    const usedPercent = toFiniteNumber(raw.used_percentage);
    if (usedPercent === null) return null;
    return { usedPercent, resetsAt: toResetMs(raw.resets_at) };
}

function windowsEqual(a, b) {
    if (a === null || b === null) return a === b;
    return a.usedPercent === b.usedPercent && a.resetsAt === b.resetsAt;
}

function readPrevious() {
    try {
        const parsed = JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf-8'));
        if (!parsed || parsed.version !== SNAPSHOT_VERSION) return null;
        const capturedAt = toFiniteNumber(parsed.capturedAt);
        if (capturedAt === null) return null;
        return parsed;
    } catch {
        return null;
    }
}

// Record the reading unless the throttle says the previous write is recent
// enough. Never throws: the caller's output must not depend on this.
function capture(payload) {
    const limits = payload && typeof payload === 'object' ? payload.rate_limits : null;
    if (!limits || typeof limits !== 'object') return;

    const fiveHour = parseWindow(limits.five_hour);
    const sevenDay = parseWindow(limits.seven_day);
    if (fiveHour === null && sevenDay === null) return;

    const now = Date.now();
    const previous = readPrevious();
    if (previous !== null) {
        const age = now - previous.capturedAt;
        if (age >= 0 && age < MIN_WRITE_INTERVAL_MS) return;
        if (age >= 0 && age < MAX_WRITE_INTERVAL_MS) {
            const changed =
                !windowsEqual(previous.fiveHour ?? null, fiveHour) ||
                !windowsEqual(previous.sevenDay ?? null, sevenDay);
            if (!changed) return;
        }
    }

    const snapshot = {
        version: SNAPSHOT_VERSION,
        capturedAt: now,
        fiveHour,
        sevenDay,
    };
    if (typeof payload.version === 'string') snapshot.cliVersion = payload.version;

    // Fan out to every track's snapshot path (the primary plus the sibling
    // tracks discovered at install time). Claude Code's statusLine slot is
    // machine-global, so this one reading belongs to every adhdev track on the
    // box; each track's daemon reads only its own directory.
    for (const target of [SNAPSHOT_PATH, ...EXTRA_SNAPSHOT_PATHS]) {
        try {
            // Write via a temp file + rename so a reader never sees a half-written
            // file, and so a killed invocation cannot truncate a good snapshot.
            // Claude Code cancels in-flight statusline scripts, so that is a real case.
            mkdirSync(dirname(target), { recursive: true });
            const temp = target + '.' + process.pid + '.tmp';
            writeFileSync(temp, JSON.stringify(snapshot), 'utf-8');
            renameSync(temp, target);
        } catch {
            // One unwritable track dir must not starve the others — and none
            // of this may reach the user's prompt (see the header note).
        }
    }
}

const stdinBuffer = await readStdin();

// Quota capture is strictly best-effort and happens before the child so a
// crash here still leaves the passthrough below to run.
try {
    capture(JSON.parse(stdinBuffer.toString('utf-8')));
} catch {
    // Unparseable payload, unwritable directory, read-only disk — none of
    // these are the user's problem while they are looking at their prompt.
}

// No original command configured: we are the whole statusline. Print nothing
// and succeed, which is what an unset statusLine would have shown.
if (!ORIGINAL_COMMAND) {
    process.exit(0);
}

const shell = process.platform === 'win32' ? process.env.COMSPEC || 'cmd.exe' : '/bin/sh';
const shellArgs = process.platform === 'win32' ? ['/d', '/s', '/c', ORIGINAL_COMMAND] : ['-c', ORIGINAL_COMMAND];

const child = spawn(shell, shellArgs, {
    stdio: ['pipe', 'inherit', 'inherit'],
    windowsHide: true,
    windowsVerbatimArguments: process.platform === 'win32',
});

// Re-feed the payload we consumed. The original command reads it from stdin
// exactly as Claude Code would have delivered it.
child.stdin.on('error', () => {
    // The child may not read stdin at all and exit first (EPIPE). Not fatal.
});
child.stdin.end(stdinBuffer);

// A missing shell or unspawnable child must not blank the status line.
child.on('error', () => process.exit(0));
// Deliberately exit 0 regardless of the child's code — see the header note.
child.on('exit', () => process.exit(0));
`;

/** Values the template needs baked in at install time. */
export interface WrapperRenderOptions {
    snapshotPath: string;
    /**
     * Sibling track snapshot files the wrapper also writes, discovered at
     * install time (see install.ts). Claude Code's `statusLine` slot is global
     * and the hook process cannot reliably tell which track's daemon spawned
     * the session, so one capture is fanned out to every track on the machine.
     */
    additionalSnapshotPaths?: string[];
    /** The user's pre-existing statusline command, or null when there was none. */
    originalCommand: string | null;
    snapshotVersion: number;
    minWriteIntervalMs: number;
    maxWriteIntervalMs: number;
}

/**
 * Produce the wrapper script with its constants substituted.
 *
 * Every substituted value goes through `JSON.stringify`, so a path containing
 * quotes or backslashes (Windows) cannot break out of its literal.
 */
export function renderWrapperScript(options: WrapperRenderOptions): string {
    return WRAPPER_TEMPLATE.replace('__ADHDEV_SNAPSHOT_PATH__', JSON.stringify(options.snapshotPath))
        .replace('__ADHDEV_EXTRA_SNAPSHOT_PATHS__', JSON.stringify(options.additionalSnapshotPaths ?? []))
        .replace('__ADHDEV_ORIGINAL_COMMAND__', JSON.stringify(options.originalCommand))
        .replace('__ADHDEV_SNAPSHOT_VERSION__', JSON.stringify(options.snapshotVersion))
        .replace('__ADHDEV_MIN_WRITE_INTERVAL_MS__', JSON.stringify(options.minWriteIntervalMs))
        .replace('__ADHDEV_MAX_WRITE_INTERVAL_MS__', JSON.stringify(options.maxWriteIntervalMs));
}
